// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/consensus/wal.proto (package tendermint.consensus, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Duration, proto3, Timestamp } from "@bufbuild/protobuf";
import { Message } from "./types_pb.js";
import { EventDataRoundState } from "../types/events_pb.js";

/**
 * MsgInfo are msgs from the reactor which may update the state
 *
 * @generated from message tendermint.consensus.MsgInfo
 */
export const MsgInfo = proto3.makeMessageType(
  "tendermint.consensus.MsgInfo",
  () => [
    { no: 1, name: "msg", kind: "message", T: Message },
    { no: 2, name: "peer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * TimeoutInfo internally generated messages which may update the state
 *
 * @generated from message tendermint.consensus.TimeoutInfo
 */
export const TimeoutInfo = proto3.makeMessageType(
  "tendermint.consensus.TimeoutInfo",
  () => [
    { no: 1, name: "duration", kind: "message", T: Duration },
    { no: 2, name: "height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "round", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "step", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * EndHeight marks the end of the given height inside WAL.
 * @internal used by scripts/wal2json util.
 *
 * @generated from message tendermint.consensus.EndHeight
 */
export const EndHeight = proto3.makeMessageType(
  "tendermint.consensus.EndHeight",
  () => [
    { no: 1, name: "height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message tendermint.consensus.WALMessage
 */
export const WALMessage = proto3.makeMessageType(
  "tendermint.consensus.WALMessage",
  () => [
    { no: 1, name: "event_data_round_state", kind: "message", T: EventDataRoundState, oneof: "sum" },
    { no: 2, name: "msg_info", kind: "message", T: MsgInfo, oneof: "sum" },
    { no: 3, name: "timeout_info", kind: "message", T: TimeoutInfo, oneof: "sum" },
    { no: 4, name: "end_height", kind: "message", T: EndHeight, oneof: "sum" },
  ],
);

/**
 * TimedWALMessage wraps WALMessage and adds Time for debugging purposes.
 *
 * @generated from message tendermint.consensus.TimedWALMessage
 */
export const TimedWALMessage = proto3.makeMessageType(
  "tendermint.consensus.TimedWALMessage",
  () => [
    { no: 1, name: "time", kind: "message", T: Timestamp },
    { no: 2, name: "msg", kind: "message", T: WALMessage },
  ],
);

