// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/types/canonical.proto (package tendermint.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { SignedMsgType } from "./types_pb.js";

/**
 * @generated from message tendermint.types.CanonicalBlockID
 */
export const CanonicalBlockID = proto3.makeMessageType(
  "tendermint.types.CanonicalBlockID",
  () => [
    { no: 1, name: "hash", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "part_set_header", kind: "message", T: CanonicalPartSetHeader },
  ],
);

/**
 * @generated from message tendermint.types.CanonicalPartSetHeader
 */
export const CanonicalPartSetHeader = proto3.makeMessageType(
  "tendermint.types.CanonicalPartSetHeader",
  () => [
    { no: 1, name: "total", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "hash", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message tendermint.types.CanonicalProposal
 */
export const CanonicalProposal = proto3.makeMessageType(
  "tendermint.types.CanonicalProposal",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(SignedMsgType) },
    { no: 2, name: "height", kind: "scalar", T: 16 /* ScalarType.SFIXED64 */ },
    { no: 3, name: "round", kind: "scalar", T: 16 /* ScalarType.SFIXED64 */ },
    { no: 4, name: "pol_round", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "block_id", kind: "message", T: CanonicalBlockID },
    { no: 6, name: "timestamp", kind: "message", T: Timestamp },
    { no: 7, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message tendermint.types.CanonicalVote
 */
export const CanonicalVote = proto3.makeMessageType(
  "tendermint.types.CanonicalVote",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(SignedMsgType) },
    { no: 2, name: "height", kind: "scalar", T: 16 /* ScalarType.SFIXED64 */ },
    { no: 3, name: "round", kind: "scalar", T: 16 /* ScalarType.SFIXED64 */ },
    { no: 4, name: "block_id", kind: "message", T: CanonicalBlockID },
    { no: 5, name: "timestamp", kind: "message", T: Timestamp },
    { no: 6, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

