// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/types/events.proto (package tendermint.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message tendermint.types.EventDataRoundState
 */
export const EventDataRoundState = proto3.makeMessageType(
  "tendermint.types.EventDataRoundState",
  () => [
    { no: 1, name: "height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "round", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "step", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

