// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/store/types.proto (package tendermint.store, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message tendermint.store.BlockStoreState
 */
export const BlockStoreState = proto3.makeMessageType(
  "tendermint.store.BlockStoreState",
  () => [
    { no: 1, name: "base", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

