// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/rpc/grpc/types.proto (package tendermint.rpc.grpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { ResponseCheckTx, ResponseDeliverTx } from "../../abci/types_pb.js";

/**
 * @generated from message tendermint.rpc.grpc.RequestPing
 */
export const RequestPing = proto3.makeMessageType(
  "tendermint.rpc.grpc.RequestPing",
  [],
);

/**
 * @generated from message tendermint.rpc.grpc.RequestBroadcastTx
 */
export const RequestBroadcastTx = proto3.makeMessageType(
  "tendermint.rpc.grpc.RequestBroadcastTx",
  () => [
    { no: 1, name: "tx", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message tendermint.rpc.grpc.ResponsePing
 */
export const ResponsePing = proto3.makeMessageType(
  "tendermint.rpc.grpc.ResponsePing",
  [],
);

/**
 * @generated from message tendermint.rpc.grpc.ResponseBroadcastTx
 */
export const ResponseBroadcastTx = proto3.makeMessageType(
  "tendermint.rpc.grpc.ResponseBroadcastTx",
  () => [
    { no: 1, name: "check_tx", kind: "message", T: ResponseCheckTx },
    { no: 2, name: "deliver_tx", kind: "message", T: ResponseDeliverTx },
  ],
);

