// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/rpc/grpc/types.proto (package tendermint.rpc.grpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { ResponseCheckTx, ResponseDeliverTx } from "../../abci/types_pb.js";

/**
 * @generated from message tendermint.rpc.grpc.RequestPing
 */
export declare class RequestPing extends Message<RequestPing> {
  constructor(data?: PartialMessage<RequestPing>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.rpc.grpc.RequestPing";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestPing;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestPing;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestPing;

  static equals(a: RequestPing | PlainMessage<RequestPing> | undefined, b: RequestPing | PlainMessage<RequestPing> | undefined): boolean;
}

/**
 * @generated from message tendermint.rpc.grpc.RequestBroadcastTx
 */
export declare class RequestBroadcastTx extends Message<RequestBroadcastTx> {
  /**
   * @generated from field: bytes tx = 1;
   */
  tx: Uint8Array;

  constructor(data?: PartialMessage<RequestBroadcastTx>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.rpc.grpc.RequestBroadcastTx";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestBroadcastTx;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestBroadcastTx;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestBroadcastTx;

  static equals(a: RequestBroadcastTx | PlainMessage<RequestBroadcastTx> | undefined, b: RequestBroadcastTx | PlainMessage<RequestBroadcastTx> | undefined): boolean;
}

/**
 * @generated from message tendermint.rpc.grpc.ResponsePing
 */
export declare class ResponsePing extends Message<ResponsePing> {
  constructor(data?: PartialMessage<ResponsePing>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.rpc.grpc.ResponsePing";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResponsePing;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResponsePing;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResponsePing;

  static equals(a: ResponsePing | PlainMessage<ResponsePing> | undefined, b: ResponsePing | PlainMessage<ResponsePing> | undefined): boolean;
}

/**
 * @generated from message tendermint.rpc.grpc.ResponseBroadcastTx
 */
export declare class ResponseBroadcastTx extends Message<ResponseBroadcastTx> {
  /**
   * @generated from field: tendermint.abci.ResponseCheckTx check_tx = 1;
   */
  checkTx?: ResponseCheckTx;

  /**
   * @generated from field: tendermint.abci.ResponseDeliverTx deliver_tx = 2;
   */
  deliverTx?: ResponseDeliverTx;

  constructor(data?: PartialMessage<ResponseBroadcastTx>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.rpc.grpc.ResponseBroadcastTx";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResponseBroadcastTx;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResponseBroadcastTx;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResponseBroadcastTx;

  static equals(a: ResponseBroadcastTx | PlainMessage<ResponseBroadcastTx> | undefined, b: ResponseBroadcastTx | PlainMessage<ResponseBroadcastTx> | undefined): boolean;
}

