// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/blocksync/types.proto (package tendermint.blocksync, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message as Message$1, proto3 } from "@bufbuild/protobuf";
import type { Block } from "../types/block_pb.js";

/**
 * BlockRequest requests a block for a specific height
 *
 * @generated from message tendermint.blocksync.BlockRequest
 */
export declare class BlockRequest extends Message$1<BlockRequest> {
  /**
   * @generated from field: int64 height = 1;
   */
  height: bigint;

  constructor(data?: PartialMessage<BlockRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.blocksync.BlockRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlockRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlockRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlockRequest;

  static equals(a: BlockRequest | PlainMessage<BlockRequest> | undefined, b: BlockRequest | PlainMessage<BlockRequest> | undefined): boolean;
}

/**
 * NoBlockResponse informs the node that the peer does not have block at the requested height
 *
 * @generated from message tendermint.blocksync.NoBlockResponse
 */
export declare class NoBlockResponse extends Message$1<NoBlockResponse> {
  /**
   * @generated from field: int64 height = 1;
   */
  height: bigint;

  constructor(data?: PartialMessage<NoBlockResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.blocksync.NoBlockResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NoBlockResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NoBlockResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NoBlockResponse;

  static equals(a: NoBlockResponse | PlainMessage<NoBlockResponse> | undefined, b: NoBlockResponse | PlainMessage<NoBlockResponse> | undefined): boolean;
}

/**
 * BlockResponse returns block to the requested
 *
 * @generated from message tendermint.blocksync.BlockResponse
 */
export declare class BlockResponse extends Message$1<BlockResponse> {
  /**
   * @generated from field: tendermint.types.Block block = 1;
   */
  block?: Block;

  constructor(data?: PartialMessage<BlockResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.blocksync.BlockResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlockResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlockResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlockResponse;

  static equals(a: BlockResponse | PlainMessage<BlockResponse> | undefined, b: BlockResponse | PlainMessage<BlockResponse> | undefined): boolean;
}

/**
 * StatusRequest requests the status of a peer.
 *
 * @generated from message tendermint.blocksync.StatusRequest
 */
export declare class StatusRequest extends Message$1<StatusRequest> {
  constructor(data?: PartialMessage<StatusRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.blocksync.StatusRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatusRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatusRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatusRequest;

  static equals(a: StatusRequest | PlainMessage<StatusRequest> | undefined, b: StatusRequest | PlainMessage<StatusRequest> | undefined): boolean;
}

/**
 * StatusResponse is a peer response to inform their status.
 *
 * @generated from message tendermint.blocksync.StatusResponse
 */
export declare class StatusResponse extends Message$1<StatusResponse> {
  /**
   * @generated from field: int64 height = 1;
   */
  height: bigint;

  /**
   * @generated from field: int64 base = 2;
   */
  base: bigint;

  constructor(data?: PartialMessage<StatusResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.blocksync.StatusResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatusResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatusResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatusResponse;

  static equals(a: StatusResponse | PlainMessage<StatusResponse> | undefined, b: StatusResponse | PlainMessage<StatusResponse> | undefined): boolean;
}

/**
 * @generated from message tendermint.blocksync.Message
 */
export declare class Message extends Message$1<Message> {
  /**
   * @generated from oneof tendermint.blocksync.Message.sum
   */
  sum: {
    /**
     * @generated from field: tendermint.blocksync.BlockRequest block_request = 1;
     */
    value: BlockRequest;
    case: "blockRequest";
  } | {
    /**
     * @generated from field: tendermint.blocksync.NoBlockResponse no_block_response = 2;
     */
    value: NoBlockResponse;
    case: "noBlockResponse";
  } | {
    /**
     * @generated from field: tendermint.blocksync.BlockResponse block_response = 3;
     */
    value: BlockResponse;
    case: "blockResponse";
  } | {
    /**
     * @generated from field: tendermint.blocksync.StatusRequest status_request = 4;
     */
    value: StatusRequest;
    case: "statusRequest";
  } | {
    /**
     * @generated from field: tendermint.blocksync.StatusResponse status_response = 5;
     */
    value: StatusResponse;
    case: "statusResponse";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<Message>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.blocksync.Message";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Message;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Message;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Message;

  static equals(a: Message | PlainMessage<Message> | undefined, b: Message | PlainMessage<Message> | undefined): boolean;
}

