// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/statesync/types.proto (package tendermint.statesync, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message tendermint.statesync.Message
 */
export const Message = proto3.makeMessageType(
  "tendermint.statesync.Message",
  () => [
    { no: 1, name: "snapshots_request", kind: "message", T: SnapshotsRequest, oneof: "sum" },
    { no: 2, name: "snapshots_response", kind: "message", T: SnapshotsResponse, oneof: "sum" },
    { no: 3, name: "chunk_request", kind: "message", T: ChunkRequest, oneof: "sum" },
    { no: 4, name: "chunk_response", kind: "message", T: ChunkResponse, oneof: "sum" },
  ],
);

/**
 * @generated from message tendermint.statesync.SnapshotsRequest
 */
export const SnapshotsRequest = proto3.makeMessageType(
  "tendermint.statesync.SnapshotsRequest",
  [],
);

/**
 * @generated from message tendermint.statesync.SnapshotsResponse
 */
export const SnapshotsResponse = proto3.makeMessageType(
  "tendermint.statesync.SnapshotsResponse",
  () => [
    { no: 1, name: "height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "format", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "chunks", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "hash", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "metadata", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message tendermint.statesync.ChunkRequest
 */
export const ChunkRequest = proto3.makeMessageType(
  "tendermint.statesync.ChunkRequest",
  () => [
    { no: 1, name: "height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "format", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "index", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message tendermint.statesync.ChunkResponse
 */
export const ChunkResponse = proto3.makeMessageType(
  "tendermint.statesync.ChunkResponse",
  () => [
    { no: 1, name: "height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "format", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "index", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "chunk", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "missing", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

