// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/state/types.proto (package tendermint.state, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { ResponseBeginBlock, ResponseDeliverTx, ResponseEndBlock } from "../abci/types_pb.js";
import { ValidatorSet } from "../types/validator_pb.js";
import { ConsensusParams } from "../types/params_pb.js";
import { Consensus } from "../version/types_pb.js";
import { BlockID } from "../types/types_pb.js";

/**
 * ABCIResponses retains the responses
 * of the various ABCI calls during block processing.
 * It is persisted to disk for each height before calling Commit.
 *
 * @generated from message tendermint.state.ABCIResponses
 */
export const ABCIResponses = proto3.makeMessageType(
  "tendermint.state.ABCIResponses",
  () => [
    { no: 1, name: "deliver_txs", kind: "message", T: ResponseDeliverTx, repeated: true },
    { no: 2, name: "end_block", kind: "message", T: ResponseEndBlock },
    { no: 3, name: "begin_block", kind: "message", T: ResponseBeginBlock },
  ],
);

/**
 * ValidatorsInfo represents the latest validator set, or the last height it changed
 *
 * @generated from message tendermint.state.ValidatorsInfo
 */
export const ValidatorsInfo = proto3.makeMessageType(
  "tendermint.state.ValidatorsInfo",
  () => [
    { no: 1, name: "validator_set", kind: "message", T: ValidatorSet },
    { no: 2, name: "last_height_changed", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * ConsensusParamsInfo represents the latest consensus params, or the last height it changed
 *
 * @generated from message tendermint.state.ConsensusParamsInfo
 */
export const ConsensusParamsInfo = proto3.makeMessageType(
  "tendermint.state.ConsensusParamsInfo",
  () => [
    { no: 1, name: "consensus_params", kind: "message", T: ConsensusParams },
    { no: 2, name: "last_height_changed", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message tendermint.state.ABCIResponsesInfo
 */
export const ABCIResponsesInfo = proto3.makeMessageType(
  "tendermint.state.ABCIResponsesInfo",
  () => [
    { no: 1, name: "abci_responses", kind: "message", T: ABCIResponses },
    { no: 2, name: "height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message tendermint.state.Version
 */
export const Version = proto3.makeMessageType(
  "tendermint.state.Version",
  () => [
    { no: 1, name: "consensus", kind: "message", T: Consensus },
    { no: 2, name: "software", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message tendermint.state.State
 */
export const State = proto3.makeMessageType(
  "tendermint.state.State",
  () => [
    { no: 1, name: "version", kind: "message", T: Version },
    { no: 2, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "initial_height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "last_block_height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "last_block_id", kind: "message", T: BlockID },
    { no: 5, name: "last_block_time", kind: "message", T: Timestamp },
    { no: 6, name: "next_validators", kind: "message", T: ValidatorSet },
    { no: 7, name: "validators", kind: "message", T: ValidatorSet },
    { no: 8, name: "last_validators", kind: "message", T: ValidatorSet },
    { no: 9, name: "last_height_validators_changed", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "consensus_params", kind: "message", T: ConsensusParams },
    { no: 11, name: "last_height_consensus_params_changed", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "last_results_hash", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 13, name: "app_hash", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

