// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/privval/types.proto (package tendermint.privval, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { PublicKey } from "../crypto/keys_pb.js";
import { Proposal, Vote } from "../types/types_pb.js";

/**
 * @generated from enum tendermint.privval.Errors
 */
export const Errors = proto3.makeEnum(
  "tendermint.privval.Errors",
  [
    {no: 0, name: "ERRORS_UNKNOWN", localName: "UNKNOWN"},
    {no: 1, name: "ERRORS_UNEXPECTED_RESPONSE", localName: "UNEXPECTED_RESPONSE"},
    {no: 2, name: "ERRORS_NO_CONNECTION", localName: "NO_CONNECTION"},
    {no: 3, name: "ERRORS_CONNECTION_TIMEOUT", localName: "CONNECTION_TIMEOUT"},
    {no: 4, name: "ERRORS_READ_TIMEOUT", localName: "READ_TIMEOUT"},
    {no: 5, name: "ERRORS_WRITE_TIMEOUT", localName: "WRITE_TIMEOUT"},
  ],
);

/**
 * @generated from message tendermint.privval.RemoteSignerError
 */
export const RemoteSignerError = proto3.makeMessageType(
  "tendermint.privval.RemoteSignerError",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * PubKeyRequest requests the consensus public key from the remote signer.
 *
 * @generated from message tendermint.privval.PubKeyRequest
 */
export const PubKeyRequest = proto3.makeMessageType(
  "tendermint.privval.PubKeyRequest",
  () => [
    { no: 1, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * PubKeyResponse is a response message containing the public key.
 *
 * @generated from message tendermint.privval.PubKeyResponse
 */
export const PubKeyResponse = proto3.makeMessageType(
  "tendermint.privval.PubKeyResponse",
  () => [
    { no: 1, name: "pub_key", kind: "message", T: PublicKey },
    { no: 2, name: "error", kind: "message", T: RemoteSignerError },
  ],
);

/**
 * SignVoteRequest is a request to sign a vote
 *
 * @generated from message tendermint.privval.SignVoteRequest
 */
export const SignVoteRequest = proto3.makeMessageType(
  "tendermint.privval.SignVoteRequest",
  () => [
    { no: 1, name: "vote", kind: "message", T: Vote },
    { no: 2, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * SignedVoteResponse is a response containing a signed vote or an error
 *
 * @generated from message tendermint.privval.SignedVoteResponse
 */
export const SignedVoteResponse = proto3.makeMessageType(
  "tendermint.privval.SignedVoteResponse",
  () => [
    { no: 1, name: "vote", kind: "message", T: Vote },
    { no: 2, name: "error", kind: "message", T: RemoteSignerError },
  ],
);

/**
 * SignProposalRequest is a request to sign a proposal
 *
 * @generated from message tendermint.privval.SignProposalRequest
 */
export const SignProposalRequest = proto3.makeMessageType(
  "tendermint.privval.SignProposalRequest",
  () => [
    { no: 1, name: "proposal", kind: "message", T: Proposal },
    { no: 2, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * SignedProposalResponse is response containing a signed proposal or an error
 *
 * @generated from message tendermint.privval.SignedProposalResponse
 */
export const SignedProposalResponse = proto3.makeMessageType(
  "tendermint.privval.SignedProposalResponse",
  () => [
    { no: 1, name: "proposal", kind: "message", T: Proposal },
    { no: 2, name: "error", kind: "message", T: RemoteSignerError },
  ],
);

/**
 * PingRequest is a request to confirm that the connection is alive.
 *
 * @generated from message tendermint.privval.PingRequest
 */
export const PingRequest = proto3.makeMessageType(
  "tendermint.privval.PingRequest",
  [],
);

/**
 * PingResponse is a response to confirm that the connection is alive.
 *
 * @generated from message tendermint.privval.PingResponse
 */
export const PingResponse = proto3.makeMessageType(
  "tendermint.privval.PingResponse",
  [],
);

/**
 * @generated from message tendermint.privval.Message
 */
export const Message = proto3.makeMessageType(
  "tendermint.privval.Message",
  () => [
    { no: 1, name: "pub_key_request", kind: "message", T: PubKeyRequest, oneof: "sum" },
    { no: 2, name: "pub_key_response", kind: "message", T: PubKeyResponse, oneof: "sum" },
    { no: 3, name: "sign_vote_request", kind: "message", T: SignVoteRequest, oneof: "sum" },
    { no: 4, name: "signed_vote_response", kind: "message", T: SignedVoteResponse, oneof: "sum" },
    { no: 5, name: "sign_proposal_request", kind: "message", T: SignProposalRequest, oneof: "sum" },
    { no: 6, name: "signed_proposal_response", kind: "message", T: SignedProposalResponse, oneof: "sum" },
    { no: 7, name: "ping_request", kind: "message", T: PingRequest, oneof: "sum" },
    { no: 8, name: "ping_response", kind: "message", T: PingResponse, oneof: "sum" },
  ],
);

