// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/mempool/types.proto (package tendermint.mempool, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message as Message$1, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message tendermint.mempool.Txs
 */
export declare class Txs extends Message$1<Txs> {
  /**
   * @generated from field: repeated bytes txs = 1;
   */
  txs: Uint8Array[];

  constructor(data?: PartialMessage<Txs>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.mempool.Txs";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Txs;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Txs;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Txs;

  static equals(a: Txs | PlainMessage<Txs> | undefined, b: Txs | PlainMessage<Txs> | undefined): boolean;
}

/**
 * @generated from message tendermint.mempool.Message
 */
export declare class Message extends Message$1<Message> {
  /**
   * @generated from oneof tendermint.mempool.Message.sum
   */
  sum: {
    /**
     * @generated from field: tendermint.mempool.Txs txs = 1;
     */
    value: Txs;
    case: "txs";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<Message>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.mempool.Message";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Message;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Message;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Message;

  static equals(a: Message | PlainMessage<Message> | undefined, b: Message | PlainMessage<Message> | undefined): boolean;
}

