// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/p2p/conn.proto (package tendermint.p2p, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { PublicKey } from "../crypto/keys_pb.js";

/**
 * @generated from message tendermint.p2p.PacketPing
 */
export const PacketPing = proto3.makeMessageType(
  "tendermint.p2p.PacketPing",
  [],
);

/**
 * @generated from message tendermint.p2p.PacketPong
 */
export const PacketPong = proto3.makeMessageType(
  "tendermint.p2p.PacketPong",
  [],
);

/**
 * @generated from message tendermint.p2p.PacketMsg
 */
export const PacketMsg = proto3.makeMessageType(
  "tendermint.p2p.PacketMsg",
  () => [
    { no: 1, name: "channel_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "eof", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message tendermint.p2p.Packet
 */
export const Packet = proto3.makeMessageType(
  "tendermint.p2p.Packet",
  () => [
    { no: 1, name: "packet_ping", kind: "message", T: PacketPing, oneof: "sum" },
    { no: 2, name: "packet_pong", kind: "message", T: PacketPong, oneof: "sum" },
    { no: 3, name: "packet_msg", kind: "message", T: PacketMsg, oneof: "sum" },
  ],
);

/**
 * @generated from message tendermint.p2p.AuthSigMessage
 */
export const AuthSigMessage = proto3.makeMessageType(
  "tendermint.p2p.AuthSigMessage",
  () => [
    { no: 1, name: "pub_key", kind: "message", T: PublicKey },
    { no: 2, name: "sig", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

