// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/p2p/pex.proto (package tendermint.p2p, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message as Message$1, proto3 } from "@bufbuild/protobuf";
import type { NetAddress } from "./types_pb.js";

/**
 * @generated from message tendermint.p2p.PexRequest
 */
export declare class PexRequest extends Message$1<PexRequest> {
  constructor(data?: PartialMessage<PexRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.p2p.PexRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PexRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PexRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PexRequest;

  static equals(a: PexRequest | PlainMessage<PexRequest> | undefined, b: PexRequest | PlainMessage<PexRequest> | undefined): boolean;
}

/**
 * @generated from message tendermint.p2p.PexAddrs
 */
export declare class PexAddrs extends Message$1<PexAddrs> {
  /**
   * @generated from field: repeated tendermint.p2p.NetAddress addrs = 1;
   */
  addrs: NetAddress[];

  constructor(data?: PartialMessage<PexAddrs>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.p2p.PexAddrs";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PexAddrs;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PexAddrs;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PexAddrs;

  static equals(a: PexAddrs | PlainMessage<PexAddrs> | undefined, b: PexAddrs | PlainMessage<PexAddrs> | undefined): boolean;
}

/**
 * @generated from message tendermint.p2p.Message
 */
export declare class Message extends Message$1<Message> {
  /**
   * @generated from oneof tendermint.p2p.Message.sum
   */
  sum: {
    /**
     * @generated from field: tendermint.p2p.PexRequest pex_request = 1;
     */
    value: PexRequest;
    case: "pexRequest";
  } | {
    /**
     * @generated from field: tendermint.p2p.PexAddrs pex_addrs = 2;
     */
    value: PexAddrs;
    case: "pexAddrs";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<Message>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tendermint.p2p.Message";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Message;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Message;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Message;

  static equals(a: Message | PlainMessage<Message> | undefined, b: Message | PlainMessage<Message> | undefined): boolean;
}

