// @generated by protoc-gen-es v1.0.0
// @generated from file tendermint/p2p/pex.proto (package tendermint.p2p, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { NetAddress } from "./types_pb.js";

/**
 * @generated from message tendermint.p2p.PexRequest
 */
export const PexRequest = proto3.makeMessageType(
  "tendermint.p2p.PexRequest",
  [],
);

/**
 * @generated from message tendermint.p2p.PexAddrs
 */
export const PexAddrs = proto3.makeMessageType(
  "tendermint.p2p.PexAddrs",
  () => [
    { no: 1, name: "addrs", kind: "message", T: NetAddress, repeated: true },
  ],
);

/**
 * @generated from message tendermint.p2p.Message
 */
export const Message = proto3.makeMessageType(
  "tendermint.p2p.Message",
  () => [
    { no: 1, name: "pex_request", kind: "message", T: PexRequest, oneof: "sum" },
    { no: 2, name: "pex_addrs", kind: "message", T: PexAddrs, oneof: "sum" },
  ],
);

